# Generated by Django 6.0.2 on 2026-03-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_profile_views'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceproject',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelanceproject',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='freelanceproject',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceproject',
            name='budget',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceproject',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelanceproject',
            name='source_url',
            field=models.URLField(max_length=500),
        ),
    ]
