# Generated by Django 6.0.2 on 2026-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_freelanceproject_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceproject',
            name='source_url',
            field=models.URLField(max_length=2000),
        ),
    ]
