# Generated by Django 6.0.2 on 2026-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
