# Generated by Django 6.0.2 on 2026-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
