# Generated by Django 6.0.2 on 2026-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='ai_tips',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
